version: '3.7'

x-app: &default-app
  build: .
  restart: always

x-env: &env
  env_file:
    - .env  

services:

  db:
    environment:
       - POSTGRES_HOST=${DB_HOST}
       - POSTGRES_PORT=${DB_PORT}
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASS}
    container_name: notify_db
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 10s
      timeout: 5s 
      retries: 5
    volumes:
      - notify_app_pg_data:/var/lib/postgresql/data

      

  api:
    <<: [*default-app, *env]
    container_name: notify_app
    # command: docker/start.sh
    ports:
      - 3000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  notify_app_pg_data:

  

