"""empty message

Revision ID: 2d119f9a35bf
Revises: 4b843daea10d
Create Date: 2024-07-10 18:47:58.634503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d119f9a35bf'
down_revision: Union[str, None] = '4b843daea10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listeners_notifications_listener_id_fkey', 'listeners_notifications', type_='foreignkey')
    op.drop_constraint('listeners_notifications_notification_id_fkey', 'listeners_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'listeners_notifications', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listeners_notifications', 'listeners', ['listener_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listeners_notifications', type_='foreignkey')
    op.drop_constraint(None, 'listeners_notifications', type_='foreignkey')
    op.create_foreign_key('listeners_notifications_notification_id_fkey', 'listeners_notifications', 'notifications', ['notification_id'], ['id'])
    op.create_foreign_key('listeners_notifications_listener_id_fkey', 'listeners_notifications', 'listeners', ['listener_id'], ['id'])
    # ### end Alembic commands ###
