"""empty message

Revision ID: c27477d2bfc0
Revises: 2b5c2f0b691c
Create Date: 2024-07-06 10:47:34.119485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27477d2bfc0'
down_revision: Union[str, None] = '2b5c2f0b691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('listeners_notifications')
    op.add_column('listeners', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listeners', 'users', ['user_id'], ['id'])
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('content', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'user_id')
    op.drop_constraint(None, 'listeners', type_='foreignkey')
    op.drop_column('listeners', 'user_id')
    op.create_table('listeners_notifications',
    sa.Column('listener_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], name='listeners_notifications_listener_id_fkey'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='listeners_notifications_notification_id_fkey'),
    sa.PrimaryKeyConstraint('listener_id', 'notification_id', name='listeners_notifications_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
